name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Build the image
      run: podman build --squash-all -t ffmpeg-static .
    - name: Compile FFmpeg
      run: podman run -v .:/ffmpeg-static:Z --userns=keep-id ffmpeg-static -v
    - name: Check the binaries
      run: |
        ./bin/ffmpeg -version
        ./bin/ffprobe -version
        ldd bin/ffmpeg || true
        ldd bin/ffprobe || true
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binaries
        path: |
          bin/ffmpeg
          bin/ffprobe
