name: Build

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Build the image
      run: podman build --squash-all -t ffmpeg-static .
    - name: Compile FFmpeg
      run: podman run -v .:/ffmpeg-static:Z ffmpeg-static
    - name: Check the binaries
      run: |
        ./bin/ffmpeg -version
        ./bin/ffprobe -version
        ldd bin/ffmpeg || true
        ldd bin/ffprobe || true
        chmod +x bin/ffmpeg
        chmod +x bin/ffprobe
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binaries
        path: |
          bin/ffmpeg
          bin/ffprobe
